name: "Status Client written in C"

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
          
      - run: gcc ./status.c status
      
      - uses: actions/upload-artifact@v3
        with:
          name: builded
          path: ./status
