name: "Status Client written in C"

on:
  push:
    branches:
      - main
      
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Compile
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          
      - run: gcc --version
      - run: ldd --version
      - run: sudo apt update
      - run: sudo apt install gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
          
      - run: |
        mkdir build
        gcc ./status.c -o ./build/status-linux-x64
        gcc -m32 ./status.c -o ./build/status-linux-x86
        aarch64-linux-gnu-gcc ./status.c -o ./build/status-linux-aarch64
        gcc-arm-linux-gnueabihf ./status.c -o ./build/status-linux-armv7l
          
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./build/status*"
          commit: main
          generateReleaseNotes: true
          draft: true
          # tag: ${{ github.event.head_commit.id }}
          tag: ${{ steps.vars.outputs.sha_short }}
