name: "Status Client written in C"

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          
      - run: gcc --version
      - run: ldd --version
          
      - run: gcc ./status.c -o status
      
      - uses: actions/upload-artifact@v3
        with:
          name: builded
          path: ./status
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./status"
          commit: master
          generateReleaseNotes: true
          draft: true
          tag: ${{ github.event.head_commit.message }}
